[package]
name = "duped-android"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
winit = { version = "0.31.0-beta.3", features = ["android-native-activity"]}
android_logger = "0.15.1"
eframe = "0.35.0"
log = "0.4.34"

[package.metadata.android]
package = "com.example.duped"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 29
target_sdk_version = 35

[package.metadata.android.application]
has_code = false
label = "Duped"
icon = "@mipmap/ic_launcher"
res = "res"


[[package.metadata.android.application.activity]]
name = "android.app.NativeActivity"
exported = true

[[package.metadata.android.application.activity.meta_data]]
name = "android.app.lib_name"
value = "duped_android"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]
