[package]
name = "duped"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
ignore = "0.4"
tempfile = "3"
clap = { version = "4", features = ["derive"] }
jwalk = "0.8.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bench]]
name = "dir_scanning"
harness = false
