import { FilledButton, ElevatedCard } from "@material";
import { AppBar } from "@material";

export { MaterialWindowAdapter } from "@material";

export component MainWindow inherits Window {
    property <int> count: 0;

    width: 100%;
    height: 100%;
 
    AppBar {
        title: "My App";
        width: parent.width;
        height: parent.height;
    }

    FilledButton {
        text: "Count: " + count;
        icon: @image-url("slint-logo.svg");
        clicked => {
            count += 1;
        }
    }
}

